on: [pull_request]
name: stylua

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      lua: ${{ steps.filter.outputs.lua }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
            lua:
              - 'lua/**'
              - 'tests/**'
  stylua:
    needs: changes
    if: ${{ needs.changes.outputs.lua == 'true' }}
    name: stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v3
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --color always --check lua
